import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  dts: false,
  sourcemap: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "@anthropic-ai/sdk",
    /^@radix-ui\/.*/,
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "cmdk",
    "vaul",
    "embla-carousel-react",
    "embla-carousel",
    "react-day-picker",
    "recharts",
    "react-hook-form",
    "@hookform/resolvers",
    "zod",
    "@dnd-kit/core",
    "@dnd-kit/sortable",
    "@dnd-kit/utilities",
    "input-otp",
    "react-resizable-panels",
    "sonner",
    "next-themes",
  ],
  treeshake: false,
});
