export type {
  AnimatedBorderCardProps,
  AnimatedCardProps,
  GlassCardProps,
  GlowPulseButtonProps,
  HolographicCardProps,
  HoverCardProps,
  MagicCardProps,
  MagneticButtonProps,
  MorphButtonProps,
  MorphVariants,
  NeonGlowCardProps,
  RippleButtonProps,
  ShimmerButtonProps,
  SpotlightCardProps,
  TiltCardProps,
} from "./MagicCard";
export {
  AnimatedBorderCard,
  AnimatedCard,
  GlassCard,
  GlowPulseButton,
  HolographicCard,
  HoverCard,
  MagicCard,
  MagneticButton,
  MorphButton,
  morphVariants,
  NeonGlowCard,
  RippleButton,
  ShimmerButton,
  SpotlightCard,
  TiltCard,
} from "./MagicCard";
